### ISSUE TITLE
can you write a demo in opengl?

### ISSUE THREAD

**Issue by wujilingfeng** [datenwolf/aveasy#4]
I am a Mathematics practitioners.so can you write  a demo that play a video  in opengl using this libray? I don't understand too many parameters.

**Comment by datenwolf** [comment]
I didn't do any maintenance work on aveasy for close to 10 years. I'm not even sure, if it even still matches ffmpeg's APIs these days.

As far as OpenGL is concerned: It's always more or less the same procedure: Make whatever video codec you're using decode a frame into buffer, load that buffer into a texture, preferrably using a pixel buffer object and through a texture with fixed storage, i.e. created with glTexStorage and the images updated with glTexSubImage, then draw that texture by the usual means.

**Comment by wujilingfeng** [comment]
Thank you for your advice!
